Procfile

I changed the order of commands due to problems with credentials during release phase on heroku.

#48 - fix heroku deploy

---

.github/workflows/deploy.yml
composer.json
composer.lock

This should close #115 and allow us to deploy application from Github. This is a suggested way of deploy after recent Github/Heroku security issues.
Heroku deploy should be triggered for every release with name starting with "v", eg. "v1.0.0".
Secrets were added to the repository:

#115 - Heroku deploy in GitHub Actions

---

resources/js/Shared/Widgets/UpcomingHolidays.vue

This would be more helpful with day of week next to the proper date. I just added it to the view.

- adding day of week to upcoming holidays

---

.github/CODEOWNERS

With outside collaborators workong on this project, I would like restrict PR approval workflow. After these changes at least one approval from someone from @blumilksoftware/toby will be required to greenlit a pull request.

- restricting PR approvals for code owners only

---

.github/workflows/check-pr-title.yml
.github/workflows/test-and-lint-js.yml
.github/workflows/test-and-lint-php.yml

I updated GHA workflows. Without it, PRs converted from drafts (like #212) won't open any checks.

- GHA workflows adjustments

---

app/Infrastructure/Http/Requests/VacationLimitRequest.php
lang/pl/validation.php
resources/js/Shared/Widgets/VacationStats.vue

This should close #240.
For now employees with vacation limit also can see statistics about remote work and other vacations:
Due to the fact that it was a minor change, I've added one more thing that I've noticed during testing - there was no maximum limit of vacation days. Now that limit is 100 days.

#240 - add statistics for remote work for employees with limit

---

app/Infrastructure/Http/Controllers/VacationRequestController.php
database/seeders/DemoSeeder.php
resources/js/Pages/VacationRequest/Show.vue

This should close #248.
When vacation request has state waiting for technical approval or waiting for administrative approval, limit for vacations is shown:

#248 - vacations indicator on vacation request view

---

.github/workflows/deploy-to-beta-manually.yml
.github/workflows/deploy-to-beta.yml
.github/workflows/deploy-to-prod.yml
Makefile

This PR contains fixups for deploy workflows:
1. Moved  git commands from Makefile to workflow, due to bug that Makefile is in locked state between deploys (Makefile is run, then changes are pulled, so changes in Makefile between deploys had no effects)
2. Splitted manual deploy to another workflow to simplify logic

#115 - Improve deployment workflows

---

.github/workflows/deploy-to-beta-manually.yml
.github/workflows/deploy-to-prod.yml

This fixes `"docker rmi" requires at least 1 argument.` output if there are no dangling docker images.

- fix docker rmi command if empty arguments

---

.github/workflows/deploy-to-beta-manually.yml
.github/workflows/run-command-on-beta.yml
Makefile

This PR adds support for running php artisan non-interactive commands on beta.
For the input, only args should be provided, without `php artisan`

- support php artisan commands on beta via workflow

---

app/Domain/Notifications/UpcomingAndOverdueMedicalExamsNotification.php
app/Domain/Notifications/UpcomingAndOverdueOhsTrainingNotification.php
app/Eloquent/Models/Profile.php
app/Infrastructure/Console/Commands/SendNotificationAboutUpcomingAndOverdueMedicalExams.php
app/Infrastructure/Console/Commands/SendNotificationAboutUpcomingAndOverdueOhsTraining.php
app/Infrastructure/Console/Kernel.php
app/Infrastructure/Http/Requests/UserRequest.php
app/Infrastructure/Http/Resources/UserFormDataResource.php
app/Infrastructure/Http/Resources/UserResource.php
composer.lock
database/migrations/2023_11_29_142131_add_dates_of_medical_exams_and_ohs_in_profiles_table.php
lang/pl.json
lang/pl/validation.php
resources/js/Pages/Users/Create.vue
resources/js/Pages/Users/Edit.vue
resources/js/Pages/Users/Index.vue
tests/Feature/UserTest.php
tests/Unit/UpcomingAndOverdueMedicalExamsNotificationTest.php
tests/Unit/UpcomingAndOverdueOhsTrainingNotificationTest.php

#337 - add dates to medical exams and ohs

---

app/Domain/Actions/VacationRequest/CreateAction.php
app/Domain/Enums/VacationType.php
app/Domain/UnavailableDaysRetriever.php
app/Domain/UserVacationStatsRetriever.php
app/Domain/VacationTypeConfigRetriever.php
app/Domain/Validation/Rules/DoesNotExceedLimitRule.php
app/Domain/Validation/Rules/MinimumOneVacationDayRule.php
app/Domain/WorkDaysCalculator.php
app/Eloquent/Models/Vacation.php
app/Eloquent/Models/YearPeriod.php
app/Infrastructure/Http/Controllers/Api/CalculateUserUnavailableDaysController.php
app/Infrastructure/Http/Controllers/Api/CalculateVacationDaysController.php
app/Infrastructure/Http/Controllers/Api/GetAvailableVacationTypesController.php
app/Infrastructure/Http/Requests/Api/CalculateUserUnavailableDaysRequest.php
app/Infrastructure/Http/Requests/Api/CalculateVacationDaysRequest.php
config/vacation_types.php
database/factories/VacationFactory.php
database/seeders/DatabaseSeeder.php
database/seeders/DemoSeeder.php
lang/pl.json
resources/js/Composables/vacationTypeInfo.js
resources/js/Pages/VacationRequest/Create.vue
tests/Feature/VacationRequestTest.php
tests/Unit/UnavailableDaysRetrieverTest.php
tests/Unit/WorkDaysCalculatorTest.php

This should close #177 
Added new "Delegation" type which can be created by administrative users, also during non-workdays

#177 - Delegations

---

config/vacation_types.php
resources/js/Pages/Users/Index.vue
tests/Feature/VacationRequestTest.php

In this pr:
- employees can't make sick vacation request - only administrator/administrative approver can do that and this request is automatically approved
- fix problem with responsiveness on users index

- block sick vacation type for employees

---

app/Domain/Actions/Slack/UpdateDailySummaryAction.php
app/Domain/Actions/VacationRequest/WaitForAdminApprovalAction.php
app/Domain/Actions/VacationRequest/WaitForTechApprovalAction.php
app/Domain/CalendarGenerator.php
app/Domain/DailySummaryRetriever.php
app/Domain/DashboardAggregator.php
app/Domain/VacationRequestStatesRetriever.php
app/Infrastructure/Http/Resources/DashboardVacationRequestResource.php
app/Infrastructure/Http/Resources/SimpleVacationRequestResource.php
config/vacation_types.php
database/seeders/DemoSeeder.php
resources/js/Pages/AnnualSummary.vue
resources/js/Pages/Calendar.vue
resources/js/Shared/CalendarDay.vue
resources/js/Shared/Layout/AppLayout.vue
resources/js/Shared/MainMenu.vue
resources/js/Shared/VacationPopup.vue
resources/js/Shared/VacationTypeCalendarIcon.vue
resources/js/Shared/Widgets/AbsenceList.vue
resources/js/Shared/Widgets/Calendar/DayComponent.vue
resources/js/Shared/Widgets/RemoteWorkList.vue
tests/Feature/VacationRequestTest.php

For now, when user goes to page "Calendar" he can hover mouse on icon and after that he see details about request. What's more, if he has permission, he can click on request number and he will be redirected to the request. 
If he doesn't have permission, the request number is not clickable, but he can see request details.
What's more, it this pr is resolved task connected with drafts. For now employee can create request about sick vacation - everybody will see in the calendar (icon will be faded a bit) and on the dashboard that the employee created the request and he is absent, but the request waits for approval. 
Moreover - all pending request are seen by all employees, but it's not the problem I think.
On the dashboard is placed information about that the request has state "pending"
On …

#378 - clickable events in calendar

---

environment/prod/deployment/beta/.env.beta
environment/prod/deployment/prod/.env.prod

This PR improves security of session cookie.
---
Scan: https://observatory.mozilla.org/
```
[Cookies](https://infosec.mozilla.org/guidelines/web_security#cookies)		-40	Session cookie set without using the Secure flag or set over HTTP
```

- use secure session cookie on beta and prod environments

---

composer.json
composer.lock
database/migrations/2023_09_14_111128_create_permission_tables.php

Should close #372.
Updated migrations for properly running tests - in migrations updates are connected with getting variables when tables are creating.
Example, **before**:
`[$columnNames["team_foreign_key"], PermissionRegistrar::$pivotPermission, $columnNames["model_morph_key"], "model_type"],`
**after**:
`[$columnNames["team_foreign_key"], $pivotPermission, $columnNames["model_morph_key"], "model_type"],
`
and  `$pivotPermission` is retrieved on the top of migration file, like that: 
`$pivotPermission = $columnNames["permission_pivot_key"] ?? "permission_id";`
Also, we can stay with normal `ids` in permissions, we do not need to change them into `uuid`.

#372 - spatie permissions update

---

app/Architecture/Providers/AppServiceProvider.php
app/Domain/Actions/VacationRequest/WaitForTechApprovalAction.php
app/Domain/CalendarGenerator.php
app/Domain/DailySummaryRetriever.php
app/Domain/DashboardAggregator.php
app/Eloquent/Models/User.php
app/Infrastructure/Http/Controllers/EquipmentController.php
app/Infrastructure/Http/Controllers/KeysController.php
app/Infrastructure/Http/Controllers/ResumeController.php
app/Infrastructure/Http/Controllers/VacationRequestController.php
app/Infrastructure/Http/Middleware/HandleInertiaRequests.php
app/Infrastructure/Http/Resources/VacationRequestResource.php
composer.json
composer.lock
storage/debugbar/.gitignore

Should close #400.
Resolved `n+1` queries for all test firstly, then I clicked through all the pages and options throughout the application and found some `n+1` issues and fixed them.
@EwelinaSkrzypacz, u must click through all the pages again and test my changes.

#400 - fixed n+1 queries in app

---

.github/workflows/deploy-to-beta-manually.yml
.github/workflows/deploy-to-prod.yml
environment/prod/deployment/beta/docker-compose.beta.yml
environment/prod/deployment/prod/docker-compose.prod.yml
readme.md

This PR changes `ghcr.io` registry to `registry.blumilk.pl`.
New images will be stored in our internal docker registry (Harbor). Toby project is publicly accessible.
The image name will be:
- for beta: 
- `registry.blumilk.pl/toby/toby:beta`
- for prod:
- `registry.blumilk.pl/toby/toby:latest`
- `registry.blumilk.pl/toby/toby:v1.2.3` (depends on releases/tags)
---
To discuss:
1. should we move old images from ghcr.io to regostry.blumilk.pl?
2. should we store images in both registries?
3. should we remove all images from ghcr.io when migration to registry.blumilk.pl will be done?

- switch beta to Blumilk's docker registry

---

renovate.json5

This PR improves Renovate config.
Actually Renovate updates all dependencies even if manually pined (`phpoffice/phpword`) and group them together with non major deps. Thats good because we want to know when new version is available.
This is invalid flow, because there was a reason to pin dependency.
In this case version 1.2.0 breaks something and it will be good to create separate PR (with manual approval in dependency dashboard, before creating PRs by Renovate)
This additional package rule fix this problem. From now package `phpoffice/phpword` will require manually approval and then separate PR will be created.

- improve renovate config for manually pined deps

---

environment/dev/app/Dockerfile
environment/prod/app/Dockerfile

This PR shows Renovate how to update `PHP_VERSION` variable in Dockerfile. 
From now it will be updated via Renovate.
Custom comments use custom managers from default config:
- https://github.com/blumilksoftware/infrastructure/blob/main/renovate/presets/default.json5#L81
This will resolve this issue:
- https://github.com/blumilksoftware/toby/pull/436#pullrequestreview-2075984615

- allow Renovate to update php docker image version

---

renovate.json5

This PR fixes renovate pin-dependencies flow.
Generic Renovate's custom manager for `_VERSION` variables in Dockerfiles breaks pin-digest flow.
Related issues and discussions:
- https://github.com/renovatebot/renovate/issues/24942
- https://github.com/renovatebot/renovate/discussions/24586
After this fix, Renovate will still update `PHP_VERSION` in Dockerfile, but won't produce errors/warnings related to pin-dependencies PR.
---
**Errors and warnings in dependency dashboard:**
```
WARN: Error updating branch: update failure
```
<details>
<summary>Renovate debug logs:</summary>
<pre>
```
2024-05-28T10:55:21.3536341Z DEBUG: getDigest(https://index.docker.io, library/php, 8.3.7-cli-bullseye) (repository=blumilksoftware/toby)
2024-05-28T10:55:21.3541799Z DEBUG: …
```

- disable pin digest for PHP_VERSION

---

app/Console/Commands/SendVacationRequestSummariesToApprovers.php
app/Notifications/VacationRequestsSummaryNotification.php

This PR fixes lazy loading `user` relation in `VacationRequest` model in queued jobs.
Sentry reports:
```
Illuminate\Database\LazyLoadingViolationException
Attempted to lazy load [user] on model [Toby\Models\VacationRequest] but lazy loading is disabled.
```
- https://blumilk.sentry.io/issues/5139914913/?project=4505271823237120&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=0
- https://blumilk.sentry.io/issues/5139914961/?project=4505271823237120&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=1
Places where `user` relation is lazy loaded
- https://github.com/blumilksoftware/toby/blob/main/app/Slack/Elements/VacationRequestsAttachment.php#L33
- https://github.com/blumilksoftware/toby/blob/main/app/Notifications/VacationRequestsSummaryNoti …

- fix lazy loading in VacationRequest model

---

.github/workflows/deploy-to-beta-manually.yml
.github/workflows/deploy-to-prod.yml
environment/prod/deployment/beta/docker-compose.beta.yml
environment/prod/deployment/prod/docker-compose.prod.yml
readme.md
renovate.json5

This PR changes docker image name in Harbor registry.
Before:
- `registry.blumilk.pl/toby/toby`
After:
- `registry.blumilk.pl/internal-public/toby`
`internal-public` project in Harbor has been already created.

- change harbor image name

---

app/Console/Commands/MigrateProfileDataIntoUserHistory.php
app/Enums/UserHistoryType.php
app/Http/Controllers/UserController.php
app/Http/Controllers/UserHistoryController.php
app/Http/Requests/UserHistoryRequest.php
app/Http/Requests/UserRequest.php
app/Http/Resources/UserHistoryResource.php
app/Http/Resources/UserResource.php
app/Models/User.php
app/Models/UserHistory.php
database/factories/UserHistoryFactory.php
database/migrations/2024_06_14_112722_add_user_history_table.php
lang/pl.json
lang/pl/validation.php
resources/js/Pages/UserHistory/Create.vue
resources/js/Pages/UserHistory/Edit.vue
resources/js/Pages/UserHistory/Index.vue
resources/js/Pages/Users/Create.vue
resources/js/Pages/Users/Edit.vue
resources/js/Pages/Users/Index.vue
routes/web.php
tests/Feature/UserHistoryTest.php

Should close #443.
Added option for administrator to manage users `employment`, `medical exams` and `ohs trainings` history.
Added artisan `toby:move-user-data-to-history` command for migrate data about `ohs training` and `medical exam` into user history.
Added tests.
Preview:
[Screencast from 18-06-24 09:24:19.webm](https://github.com/blumilksoftware/toby/assets/29115024/8d502c1d-c84e-4831-9514-61eef00d171c)

#443 - employment, medical and ohs history

---

app/Console/Commands/MigrateProfileDataIntoUserHistory.php
app/Domain/EmployeesMilestonesRetriever.php
app/Http/Requests/UserHistoryRequest.php
app/Http/Resources/EmployeeMilestoneResource.php
app/Http/Resources/UserHistoryResource.php
app/Models/User.php
app/Models/UserHistory.php
database/migrations/2024_07_03_120018_add_blumilk_flag_in_user_history_table.php
resources/js/Pages/UserHistory/Create.vue
resources/js/Pages/UserHistory/Edit.vue
resources/js/Pages/UserHistory/Index.vue
tests/Feature/EmployeesMilestonesTest.php

Should close #445.
Changed the way seniority is calculated - after this PR we will receive information from the user's employment history, taking into account changes in contracts. Updated tests.

#445 - seniority calculation refactor

---

app/Actions/OvertimeRequest/WaitForTechApprovalAction.php
app/Console/Commands/SendOvertimeRequestSummariesToApprovers.php
app/Console/Commands/SendVacationRequestSummariesToApprovers.php
app/Notifications/OvertimeRequestNotification.php
app/Notifications/OvertimeRequestsSummaryNotification.php
app/Notifications/OvertimeRequestsWaitsForApprovalNotification.php
app/Notifications/VacationRequestWaitsForApprovalNotification.php
app/Slack/Elements/OvertimeRequestsAttachment.php
app/Slack/SlackActionController.php
config/permission.php
lang/pl.json
resources/js/Composables/permissionInfo.js
resources/js/Pages/OvertimeRequest/Show.vue
routes/api.php
routes/console.php
tests/Feature/PermissionTest.php
tests/Unit/SendOvertimeRequestSummariesTest.php

In this pr I added Slack notification about overtime requests. Now from Slack the technical approver/user with right permission can approve or reject overtime.
Also I added notification with overtimes waiting for approval. It works very similar to vacation requests - every weekday about 8:30 users with right permissions will receive information about overtimes that waits for approval.
This should finally close #444.

#444 - add notification to Slack about overtime

---

.github/workflows/test-and-lint-js.yml
app/Http/Controllers/VacationCalendarController.php
lang/pl.json
package-lock.json
package.json
resources/js/Pages/Calendar.vue
routes/web.php
tests/Feature/CalendarTest.php

Connected with #377.
Added dropdown with months to switching months faster. 
Added possibility of changing years from calendar buttons also.
Preview:
[Screencast from 17-07-24 14:59:52.webm](https://github.com/user-attachments/assets/7bce52c9-338b-426e-adb0-b74c6ea8b6a4)

#377 - calendar months dropdown

---

resources/js/Pages/Calendar.vue
resources/js/Pages/VacationRequest/IndexForApprovers.vue

#501 - calendar reset button

---

resources/js/Pages/Equipment/IndexForEmployee.vue
resources/js/Pages/Users/Show.vue

In this pr:
- added import AppLayout to page `IndexForEmployee`
- remove unused import from `UserShow`

- add navigation to page with employee equipment

---

app/Actions/VacationRequest/ApproveAction.php
app/Actions/VacationRequest/CancelAction.php

In the `ApproveAction` and `CancelAction`, users with permission to receive notifications about vacation requests were receiving duplicate notifications if they were also the request submitter.

- fix double notifications

---

app/Domain/UserBenefitsRetriever.php
app/Http/Controllers/BenefitController.php
app/Http/Resources/BenefitResource.php
resources/js/Pages/Benefits/Benefits.vue
resources/js/Pages/Calendar.vue

In this pr I added info about owing benefits on benefits index page - if user has a benefit, next to benefit name the icon is displayed.
Also I fixed an issue in the calendar where changing the date to the same month but a different year did not refresh the view. The calendar now refreshes correctly with every date change.

- Add info about benefits on list

---

.env.example
docker-compose.yml
environment/dev/app/supervisord.conf
vite.config.js

This pull request includes several changes aimed at updating environment configurations, improving Docker setup, and modifying the Vite configuration. The most important changes include updating environment variables in the `.env.example` file, modifying the `docker-compose.yml` file to use new host names, and updating the Vite configuration to enhance server setup.
* Updated `APP_URL` and added new host name variables for Docker in the `.env.example` file. (`[[1]](diffhunk://#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cL5-R5)`, `[[2]](diffhunk://#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cL67-R71)`)
* Modified `docker-compose.yml` to use new host names and added configurations for the Vite dev server and Mailpit service. …

- adjust new blumilk environment

---

app/Enums/VacationType.php
config/vacation_types.php
tests/Feature/VacationRequestTest.php

This pr prevents employees from creating time-in-lieu requests
Thanks to @MichalMyskow :wink: 
Also in this pr I changed vacation type order in create a vacation request form. Now types are ordered by most popular in our company

- prevent employee for creating time in lieu request
