- app/Infrastructure/Http/Controllers/Api/CalculateUserUnavailableDaysController.php
- app/Infrastructure/Http/Controllers/Api/CalculateVacationDaysController.php
- app/Infrastructure/Http/Requests/Api/CalculateUserUnavailableDaysRequest.php
- resources/js/Pages/VacationRequest/Create.vue
- routes/api.php
> #95 - unavailable days

- app/Infrastructure/Http/Controllers/GoogleController.php
- tests/Feature/MonthlyUsageTest.php
- tests/Feature/VacationCalendarTest.php
- tests/Feature/VacationRequestTest.php
I've added some tests, mostly focuses on permissions
> - Permissions tests

- Procfile
- composer.json
- composer.lock
Laravel 9.6.0 causes connection problems with redis, so I've reverted to 9.5.x for now.
> #48 - fix heroku deploy

- app/Architecture/Providers/ObserverServiceProvider.php
- app/Eloquent/Models/VacationRequest.php
- app/Eloquent/Models/YearPeriod.php
- app/Eloquent/Observers/VacationRequestObserver.php
- app/Infrastructure/Console/Commands/RebuildDocumentNumberingSystem.php
- database/migrations/2022_04_04_135927_add_name_column_in_vacation_requests_table.php
Change the document numbering system to {number}/{year}
There is command `toby:rebuild-document-numbering-system` that rebuilds existing data in db to the new system.
> - change numbering system

- app/Domain/Enums/VacationType.php
- app/Domain/TimesheetExport.php
- app/Domain/TimesheetPerUserSheet.php
- app/Domain/UserVacationStatsRetriever.php
- app/Domain/VacationTypeConfigRetriever.php
- app/Domain/Validation/Rules/DoesNotExceedLimitRule.php
- app/Infrastructure/Http/Controllers/Api/GetAvailableVacationTypesController.php
- app/Infrastructure/Http/Controllers/TimesheetController.php
- app/Infrastructure/Http/Controllers/VacationRequestController.php
- app/Infrastructure/Http/Requests/Api/GetAvailableVacationTypesRequest.php
- config/vacation_types.php
- resources/js/Composables/vacationTypeInfo.js
- resources/js/Pages/MonthlyUsage.vue
- resources/js/Pages/VacationLimits.vue
- resources/js/Pages/VacationRequest/Create.vue
- resources/js/Pages/VacationRequest/Index.vue
- resources/js/Pages/VacationRequest/IndexForApprovers.vue
- resources/js/Pages/VacationRequest/Show.vue
- resources/js/Shared/MainMenu.vue
- resources/lang/pl.json
- routes/api.php
- tests/Feature/VacationCalendarTest.php
> #108 - types of vacation request

- composer.json
- composer.lock
- config/cache.php
- config/database.php
- config/queue.php
- config/session.php
> #107 - bump laravel

- app/Infrastructure/Http/Controllers/VacationRequestController.php
> #122 - fix missing people in vacation request view

- resources/js/Pages/VacationRequest/Index.vue
- resources/js/Pages/VacationRequest/IndexForApprovers.vue
> #138 - fix tables on safari

- app/Infrastructure/Http/Controllers/VacationRequestController.php
- resources/js/Pages/VacationRequest/IndexForApprovers.vue
> - vacation type filter

- licence.md
> - MIT license added

- resources/js/Pages/Holidays/Index.vue
- resources/js/Pages/Keys.vue
- resources/js/Pages/Resumes/Index.vue
- resources/js/Pages/Technologies.vue
- resources/js/Pages/Users/Index.vue
- resources/js/Pages/VacationRequest/IndexForApprovers.vue
- resources/js/Shared/Feedbacks/EmptyState.vue
- resources/js/Shared/Widgets/PendingVacationRequests.vue
- resources/js/Shared/Widgets/UserVacationRequests.vue
> #150 - empty states

- resources/js/Pages/Holidays/Create.vue
- resources/js/Pages/Holidays/Edit.vue
- resources/js/Pages/Resumes/Create.vue
- resources/js/Pages/Resumes/Edit.vue
- resources/js/Pages/Technologies.vue
- resources/js/Pages/Users/Create.vue
- resources/js/Pages/Users/Edit.vue
- resources/js/Pages/VacationLimits.vue
- resources/js/Pages/VacationRequest/Create.vue
This should close #153 
**Changed for:**
- Edit users
- Edit CV
- Edit vacation limits
- Edit holidays
**Presentation:**
https://user-images.githubusercontent.com/1353655/172369461-f1bdd0db-21e7-4c09-8c0c-739e8cf637f0.mp4
> #153 - button behaviour in form editing

- lang/pl.json
- resources/js/Composables/vacationTypeInfo.js
- resources/js/Pages/Calendar.vue
- resources/js/Shared/MainMenu.vue
In this PR I:
* removed word "urlop" from calendar as they are now available for everyone, including people without vacation rights
* restyle "Opieka nad dzieckiem art 188 kp" to "Opieka nad dzieckiem (art. 188 kp)"
> - phrasing

- docker-compose.yml
Changes:
- changed data path for: **database**, **redis**
> - fix docker volumes

- resources/js/Pages/VacationRequest/Create.vue
This should close #173 
Fixed the behaviour of the button for a form with an entered date.
https://user-images.githubusercontent.com/1353655/173825915-1fc5edf2-0be5-43b2-9912-df33bedb0425.mp4
> #173 - button behaviour in creating request

- app/Eloquent/Models/User.php
- app/Infrastructure/Http/Controllers/UserController.php
- package-lock.json
- resources/js/Pages/Users/Index.vue
It should close #180 
[Issue-180.webm](https://user-images.githubusercontent.com/48356242/177719766-bdb5b6d9-b00c-4c16-92e2-ded33d399600.webm)
> #180 - generate users e-mails list

- app/Eloquent/Models/Key.php
- app/Eloquent/Models/Profile.php
- app/Eloquent/Models/Resume.php
- app/Eloquent/Models/Vacation.php
- app/Eloquent/Models/VacationLimit.php
- app/Eloquent/Models/VacationRequest.php
- app/Eloquent/Models/VacationRequestActivity.php
- app/Infrastructure/Http/Controllers/MonthlyUsageController.php
- app/Infrastructure/Http/Requests/ResumeRequest.php
- app/Infrastructure/Http/Resources/ResumeFormResource.php
- package-lock.json
- package.json
- resources/js/Pages/Resumes/Edit.vue
> #185 - fix list of vacation request

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/check-pr-title.yml
- .github/workflows/test-and-lint-js.yml
- .github/workflows/test-and-lint-php.yml
- app/Infrastructure/Http/Requests/AssignedBenefitsRequest.php
- resources/js/Pages/BenefitsReport/AssignedBenefits.vue
- resources/js/Pages/BenefitsReport/BenefitsReport.vue
> #198 - sticky users column in benefits

- app/Domain/BenefitsReportTimesheet.php
- resources/js/Shared/Widgets/RemoteWorkList.vue
> #200 - set columns width in benefits Excel report

- config/ui-avatars.php
> #204 - fix quality of avatars

- resources/js/Pages/BenefitsReport/AssignedBenefits.vue
> #206 - fix assigned benefits

- resources/js/Pages/Dashboard.vue
I think that remote work list is more dynamic per every day than birthdays list, so it could be more on top.
> - dashboard components order

- app/Eloquent/Models/VacationRequest.php
- app/Infrastructure/Http/Controllers/VacationRequestController.php
- resources/js/Pages/VacationRequest/Index.vue
This should close #241.
https://user-images.githubusercontent.com/56546832/194243496-735db2f8-f904-44f0-b5bd-f413630bfb0a.mp4
> #241 - add option to hide remote work requests on requests list

- docker-compose.beta.yml
- docker-compose.prod.yml
- environment/prod/nginx/templates/default.conf.template
Added `docker-compose.prod.yml` file for production containers.
Improved nginx config.
Added errors for docker-compose variables
Due to implement scheduler and worker as a containers, I think we can close issue #133 
From now, jobs will be processed from the Redis queue by worker, scheduled stuff will be processed by scheduler.
closes #133
> #218 - VPS prod setup

- resources/js/Shared/Widgets/UpcomingHolidays.vue
> - Capitalize letters in upcoming holiday tile

- app/Domain/Policies/VacationRequestPolicy.php
- app/Domain/UserVacationStatsRetriever.php
- tests/Feature/VacationRequestTest.php
> #227 - canceling remote work request

- app/Domain/DailySummaryRetriever.php
Little fix to birthday tile - for now it shows only three next birthdays, not all of them.
> - fix on birthday tile

- app/Infrastructure/Slack/Handlers/DailySummary.php
Now birthdays on Slack shows properly.
> - fix birthdays on daily slack summary

- .github/workflows/deploy-to-beta.yml
- .github/workflows/deploy-to-prod.yml
- Makefile
This PR fix SSH action, where env variable `BRANCH_NAME` has not been passed to the make command
Reference
https://github.com/appleboy/ssh-action/issues/166
> #115 - fix SSH script in deploy workflows

- .github/workflows/deploy-to-beta.yml
- .github/workflows/deploy-to-prod.yml
- Makefile
- environment/scripts/post-deploy-actions.sh
- environment/scripts/reload-config.sh
- readme.md
Added `git config --global --add safe.directory <PATH TO PROJECT>` for bot user which is used during deployment.
> #115 - Adjust deployment

- readme.md
Tests for deployment to beta.
by comment:
https://github.com/blumilksoftware/toby/actions/runs/3639596993
manually:
https://github.com/blumilksoftware/toby/actions/runs/3639612895
> #115 - test deployment

- app/Eloquent/Observers/UserObserver.php
- app/Infrastructure/Http/Controllers/LocalLoginController.php
- app/Infrastructure/Http/Controllers/LoginController.php
- app/Infrastructure/Http/Middleware/CheckIfLocalEnvironment.php
- app/Infrastructure/Http/Requests/LocalLoginRequest.php
- database/factories/UserFactory.php
- lang/pl.json
- lang/pl/validation.php
- resources/js/Pages/LocalLogin.vue
- resources/js/Pages/Login.vue
- routes/web.php
> #226 - Login without Google on local environment

- routes/web.php
I mistakenly deleted one of the Google login routes in the previous PR https://github.com/blumilksoftware/toby/pull/343
> - Fix google login

- resources/js/Shared/MainMenu.vue
> #309 - sidebar last element position

- app/Domain/Actions/VacationRequest/CreateAction.php
> #352 - change order

- config/vacation_types.php
- tests/Feature/VacationRequestTest.php
> #359 - absence for employees who has employment contract

- app/Infrastructure/Http/Rules/YearPeriodExists.php
- app/Infrastructure/Slack/Rules/SlackUserExistsRule.php
- tests/Unit/SlackUserExistsRuleTest.php
- tests/Unit/YearPeriodExistsRuleTest.php
> #335 - refactor deprecated rule contract

- Makefile
- app/Domain/UserBenefitsRetriever.php
- app/Eloquent/Models/BenefitsReport.php
- app/Infrastructure/Http/Controllers/AssignedBenefitController.php
- app/Infrastructure/Http/Controllers/BenefitsReportController.php
- lang/pl.json
- resources/js/Pages/BenefitsReport/Index.vue
- routes/web.php
- tests/Feature/AssignedBenefitsTest.php
- tests/Feature/BenefitsReportTest.php
> #232 - delete benefits report

- app/Infrastructure/Http/Resources/DashboardVacationRequestResource.php
> #386 - fix incorrect data display in vacation pop up

- app/Domain/DailySummaryRetriever.php
- app/Domain/DashboardAggregator.php
- codestyle.php
- composer.json
- composer.lock
- config/app.php
- config/model-states.php
- config/permission.php
- config/telescope.php
- config/ui-avatars.php
I updated invalid ordering of users on dashboard. I also updated codestyle package and ran it thru the project.
> - alphabetically ordered vacations

- app/Domain/DailySummaryRetriever.php
- app/Domain/EmployeesMilestonesRetriever.php
- tests/Feature/EmployeesMilestonesTest.php
Should close #421.
Fixed sorting birthdays, updated tests.
> #421 - birthday bug

- resources/js/Pages/VacationRequest/Show.vue
Additional calendar was not visible when I removed adminitrative role from myself. This PR should fix that.
> #327 - handy calendar tweaks

- app/Console/Commands/MigrateProfileDataIntoUserHistory.php
Connected with #452.
Updated command.
> #452 - updated migration command

- resources/js/Pages/VacationRequest/Show.vue
> #419 - fixed double approval error

- app/Domain/ResumeGenerator.php
- composer.json
- composer.lock
- storage/app/resumes/.gitignore
- tests/Feature/BenefitsReportTest.php
- tests/Feature/ResumeTest.php
- tests/Feature/VacationRequestTest.php
> #420 - updated phpoffice package

- app/Http/Resources/UserFormDataResource.php
- resources/js/Pages/Users/Create.vue
- resources/js/Pages/Users/Edit.vue
Fixed bug connected with #452.
> #452 - bug fix

- resources/views/app.blade.php
Connected with @mtracz [comment](https://github.com/blumilksoftware/toby/pull/412#discussion_r1698017545).
> #395 - updated if statement for csp header

- app/Domain/MonthWorkingHoursCalculator.php
- app/Http/Controllers/VacationCalendarController.php
- app/Models/User.php
- config/toby.php
- resources/js/Pages/Calendar.vue
Should close #479.
Added information on calendar about number of working hours in specific month (excluding vacations, holidays etc.).
Preview:
[Screencast from 01-08-24 12:33:25.webm](https://github.com/user-attachments/assets/23f946cf-e34c-4185-9069-0e85204ad62e)
> #479 - number of working hours

- app/Http/Controllers/OvertimeTimesheetController.php
- app/Http/Controllers/TimesheetController.php
- app/Http/Controllers/VacationCalendarController.php
> #503 - fix calendar

- app/Http/Controllers/TimesheetController.php
Fixes a bug where absences were incorrectly counted as working hours in the timesheet report after a user switched from a commission contract to an employment contract. This PR ensures absences are correctly handled after the contract type changes.
> - Fix absence counting after contract change

- app/Actions/VacationRequest/BulkCreateAction.php
- app/Http/Controllers/VacationRequestController.php
- app/Http/Requests/BulkVacationRequestRequest.php
- app/Notifications/VacationRequestNotification.php
- package-lock.json
- resources/js/Pages/VacationRequest/BulkCreate.vue
- resources/js/Pages/VacationRequest/IndexForApprovers.vue
- routes/web.php
- tests/Feature/VacationRequestTest.php
> #491 - request bulk action
